### PR TITLE
Added test on the velocity operator, and computation of the group velocities from the velocity operator

### PR DESCRIPTION
**Pull request by MSimoncelli**
Thank you for all the work @atztogo . I have implemented the computation of the group velocities from the velocity operator.
RTA solution works perfectly, both at the Wigner and Peierls-Boltzmann levels. I have tested the code on CsPbBr3 (with read-gamma option) and it works perfectly. 
Both test_kappa_LBTE.py and test_kappa_LBTE_Wigner.py are failing on my Mac after the manual update (they were failing before this pull request), but they work on GitHub and on a linux system.
I spent some time to look for the problem, but the code has changed considerably compared to the previous version and I haven't found how to solve. Are test_kappa_LBTE.py and test_kappa_LBTE_Wigner.py working on your Mac?

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks @MSimoncelli for checking PR #83.

> Are test_kappa_LBTE.py and test_kappa_LBTE_Wigner.py working on your Mac?

Yes both on Intel mac and m1 mac.

You should merge develop first before modifying your develop.
https://github.com/MSimoncelli/phono3py/commit/f10605aa52e41d14ed6e3443d0ae51428a610365

Smaller PR is better. So before your struggling, could you contact me more often?

Here, please do not modify `.gitignore` and do not add unnecessary files in repository,
https://github.com/MSimoncelli/phono3py/commit/b3bdf644656e1c09270ec099fe83f90ac092c4dc
https://github.com/MSimoncelli/phono3py/commit/eb597a41c817ca523ae4785dc241528586ef1b47
https://github.com/MSimoncelli/phono3py/commit/5be50f17abfc69f437514614b6c57aea792e26c3
Perhaps do you use the command `git commit  -a` (or `git add .`)? This is not recommended. First find the modified files `git status`, and specify necessary files to be committed by like `git commit file-name1 file-name2`. You can revert the changes of files by `git commit -- file-name`.

I think the test of the velocity operation exists in the develop branch if I understand correctly. Why did you need reintroduction? Maybe I am wrong.
https://github.com/MSimoncelli/phono3py/commit/b775211ec83bbc30415ee7d75dab32198d251ed3

Please do not touch the code before fixing your issue running tests of the phono3py/develop.
https://github.com/MSimoncelli/phono3py/commit/7292ec0b34d5fd2f3fec019d6baafad9a5e35dda

Please run pre-commit hooks before `git commit`. A short instruction is written `README.md` here
https://github.com/phonopy/phono3py

**Comment by MSimoncelli** [comment]
Thanks  @atztogo for going thorough all the comments, and for the guidelines about git.

I didn't expect the gitignore and related unnecessary files to sync from my fork to your repo, apologises for that.

Anyway, aside from these git-related issues, I modified and tested the code on a linux system.

The test on the velocity operator was not updated to the last version (committed in phonopy few days ago), and it was skipped in the manual merge. I have updated such test; it is successful on a Linux system, on github, and on my Mac. 

I have updated the computation of the group velocity from the velocity operator in the case of degeneracies. 
This is needed only when the diagonal elements of the velocity operator are used as group velocities in the direct solution of the population (particle-like) part of the Wigner equation.
This is expected to produce no changes in the RTA conductivity. I tested CsPbBr3 after this modification and indeed found perfectly compatible results (less than 0.001 W/mK in the thermal conductivity). Then ran also the other tests on the conductivity test_kappa_RTA_si_nosym fails with tolerance 0.5. Increasing the test tolerance to 0.8 results in a pass. I have not understood what we are testing here, since I would expect the conductivity tensor of silicon to be diagonal and isotropic, but the reference results for this test in the standard phono3py version (before the Wigner update) are non-diagonal and non isotropic. I notices that in the reference tensor value for this test in the standard phono3py versuion, the difference between the diagonal components of the expected-to-be-diagonal tensor are of about 1 W/mK, thus using 0.8 W/mK as tolerance seems reasonable.

Do not hesitate to let me know if you need any further action from my side! 
Thanks, Michele

**Comment by atztogo** [comment]
I understand what you wrote. Just for convenience, could you abandon this PR and recreate it cleanly? I think this is rather easy for you to do so than for me to struggle on merging it. The points are as I wrote above, e.g., first merging phono3py/develop to the point where you started to work on this PR or clone phono3py repository and start working on it. If possible, the later is better. You tend to write comments (lines starting `#`) inside code, but often the code is updated but not the comment, then the code and comment start to disagree. So it is recommended to write minimum comments. If we need to explain something, it is good to think either if it is written as comment line or in docstring. Please run pre-commit before the commit as explained above. In addition, you probably work on your develop branch of your phono3py repository. But it is good to make another branch by 

```
% git checkout -b topic_branch_name
```
In this way, it becomes easier to go back to the point where you started working on the parent code and to compare with other topic branches. Git is designed to use branches to communicate between developers in collaboration.

One question. I see your update
```python
gv = np.einsum("iij->ij", gv_operator).real
```
Do you assume the first two dimensions have the same size? And is it truer?

**Comment by MSimoncelli** [comment]
Got it, thanks for the explanations. I'll discard this PR and do a single PR.

Concerning your question, the answer is yes.
At fixed q-point and cartesian direction, the velocity operator is a square matrix of size (3*N_atoms_in_primitive_cell)x(3*N_atoms_in_primitive_cell).

In absence of degeneracies, the group velocities at fixed q-point and at fixed direction are simply the diagonal elements of the aforementioned square matrix. If degeneracies are present, the group velocities are obtained diagonalising the velocity operator in the degenerate subspace. Hope this fully answers your questions, do not hesitate to get in touch if needed.

**Comment by atztogo** [comment]
> I'll discard this PR and do a single-commit PR.

Thanks.

About `gv`, I understand you are correct theoretically. But your `gv_operator` is allocated as
https://github.com/phonopy/phono3py/blob/993f10781dfc06433db081e2228d9a04f4986172/phono3py/conductivity/rta.py#L809-L811

Here, `num_band0` can be different from `nat3`. `num_band0 != nat3` when `--bi` option is specified.

**Comment by MSimoncelli** [comment]
Ok I see what you mean. I'll take care of that

**Pull request closed without merging**
