### PR TITLE
[WIP] Merge Wigner thermal conductivity formula

### PR DESCRIPTION
**Pull request by atztogo**
Manual merging of the following PRs into phono3py.

* https://github.com/phonopy/phonopy/pull/178 (working)
* https://github.com/phonopy/phono3py/pull/64 (not yet)

### CODE REVIEW

**Comment by atztogo** [comment]
@MSimoncelli, I have roughly done merging your PR #64. I'm sorry for my slow work. I needed to find free days that I can concentrate only on this merge.

I separated your code lines inserted into the existing code. Now the code specific for your method is independent. I tried to keep your code as much as possible for your to read easily. I reorganize the code structure to include your code, so your code lines were moved to the following parts:

- `phono3py/conductivity/wigner.py`
- `phono3py/conductivity/rta.py::ConductivityWignerRTA`
- `phono3py/conductivity/direct_solution.py::ConductivityWignerLBTE`
- `test/conductivity/test_kappa_LBTE_Wigner.py`
- `test/conductivity/test_kappa_RTA_Wigner.py`
- `test/phonon/test_velocity_operator.py`

Tests you wrote for thermal conductivity pass, but not velocity operator. So I skip the tests in `test/phonon/test_velocity_operator.py`.

I don't carefully check the data stored in `kappa-xxx.hdf5` file.

I merge this into develop. Please pull the develop branch and send PR if you need to fix or update. When your send PR, it is always welcome smaller PRs than a large PR. This makes review easy.

## Comments

### How to active from command line

I made `--wigner` command line option. This works with `--br` or `--lbte` to activate your method.

### Conventional group velocity in your code

It seems the method `_set_gv_op` is not used. The method `_set_gv_operator` is used. In `_set_gv_operator`, (conventional) group velocity is not set to `self._gv`. So I added the following lines in this method:

```python
        self._gv[i_data] = [
            self._gv_operator[i_data, bi, i].real
            for i, bi in enumerate(self._pp.band_indices)
        ]
```

I hope this is correct.

### Unused variables

`self._kappa_TOT_exact` and `self._kappa_TOT_RTA` in direct-solution (LBTE) seem not be used anywhere.

### Complex data type
The numpy arrays of complex type have `dtype` of `complex_dtype = "c%d" % (np.dtype("double").itemsize * 2)` to agree with C complex structure of two `double` values. `dtype=complex` may not be very safe in phono3py implementation, which is a local rule, because the data may be passed to C-API and the code in C doesn't check the numerical types carefully.

**Comment by atztogo** [comment]
@MSimoncelli, your code emits many warnings and now I am fixing it. I have a question. In the following lines `self._kappa_C` has the `double` dtype, but `self._mode_kappa_C` has the `complex` dtype. I guess the total sum of complex values results in real, but computer can not see it. So simply implicit cast is made at the assignment by numpy, but this kindly raises warning. In this case, we have to make it explicit to remove the warning. Can I write the right hand side such as `(...).real`, i.e., my guess is correct?

https://github.com/phonopy/phono3py/blob/b6076070d65d38d380dd8b3b0abe4d0606b8fec0/phono3py/conductivity/direct_solution.py#L1592-L1594

**Comment by MSimoncelli** [comment]
Yes, your guess is correct, you can write the right hand side such as (...).real.

Michele

**Comment by atztogo** [comment]
Thanks @MSimoncelli for your clarification. Fixed at PR #86.

**Pull request merged**
