### PR TITLE
Implementation of the the Wigner thermal conductivity formula

### PR DESCRIPTION
**Pull request by MSimoncelli**
Implemented the thermal conductivity formula derived from the Wigner formulation of thermal transport in solids  [Simoncelli, Marzari, Mauri, Nature Physics, 15 (8), 809 (2019); Simoncelli, Marzari, Mauri arXiv:2112.06897 (2021)].

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks @MSimoncelli. I will need to understand how it works, and may not be able to do it very quickly.
Could you write tests and documentations? The documentation would be good to be written as an independent page such as http://phonopy.github.io/phono3py/direct-solution.html. Please ask freely how to do them if you have any questions.

**Comment by MSimoncelli** [comment]
Thanks @atztogo for the prompt reply. I will write the documentation as an independent page. Also, I would need more information about tests. I am available to discuss via zoom if needed. Thank you very much.

**Comment by atztogo** [comment]
Manual merging process can be seen at PR #83.

**Comment by atztogo** [comment]
I close this PR because the code is merged into develop branch. See PR #83.

**Pull request closed without merging**
