### PR TITLE
Implemented computation of the group velocities from the velocity operator

### PR DESCRIPTION
**Pull request by MSimoncelli**
Also added a test on the velocity operator. 

Works also with --bi option. In fact:
in wigner.py, the variable gv_operator at line 119 has always shape [nat3, nat3,3];
the variable self._gv_operator[i_data] defined at line 809 in rta.py has shape [num_band0, nat3, 3]. 

Everything works fine because at line 120 in in wigner.py we assign values accounting for the different shapes:
        self._gv_operator[i_data] = gv_operator[self._pp.get_band_indices(), :, :]        

I have tested the code also on CsPbBr3 with --read-gamma option and obtained results perfectly compatible with those computed with the old version of the code on my fork.

Hope this is ok, do not hesitate to let me know if you need anything else from my side.
Thanks a lot for your help,
Michele 

P.S. I ran pre-commit run --all-files , but when I did the pull request the auto fixes from pre-commit.com hooks found one tab that surprisingly was not recognised neither by the pre-commit.com hooks on my system nor by my GitHub.

### CODE REVIEW

**Comment by atztogo** [comment]
Thanks @MSimoncelli.

Have you run `pre-commit install` before `pre-commit run --all-files`? On my computer, I got same error from pre-commit as found here https://results.pre-commit.ci/run/github/48793261/1646968182.pmxJleasSWGf8WLfmqJNjQ.

Yes, as you commented, `ph_si` fixture didn't exist. So I added it on develop branch. Could you activate (i.e. remove skip) `test_gv_operator_si`? The procedure is as follows. First please pull the latest phono3py develop to your local branch

```
% git pull https://github.com/phonopy/phono3py.git develop
```

Then activate the `test_gv_operator_si` and run `pytest`. As I wrote above, maybe `pre-commit install` is necessary for you.

```
% pre-commit install
% pre-commit run --all-files
```

After these, you can commit and push. Then your change is automatically reflected to this PR.

**Comment by MSimoncelli** [comment]
Thanks a lot for the help @atztogo !

I performed the modifications you requested.

Concerning your question on pre-commit - yes, I installed pre-commit before running it on my system (see e.g. intermediate commit here https://github.com/MSimoncelli/phono3py/commit/8c548ae2b07c47e7db330e8fafed2654b9a5e02d ).
I ignored the flake8 error because it was due to a long comment on skipping the test on the velocity operator on Si, I noticed that [pre-commit.ci] was not pushing additional commits because of this, and since I expected that line to be removed by a future commit, I just left it. 
My previous comment was just to apologise for the additional commit done by [pre-commit.ci] to remove a tab which apparently remained in the code even after I ran pre-commit.

**Comment by atztogo** [comment]
Great @MSimoncelli. Thanks. Merged.

> I ignored the flake8 error because it was due to a long comment on skipping the test on the velocity operator on Si, I noticed that [pre-commit.ci] was not pushing additional commits because of this, and since I expected that line to be removed by a future commit, I just left it.

In this case, you could let me know it to fix it. You left the error, so the tests did not run on github workflow by pre-commit blocking.

In addition, you can make a new branch to work on. If you are on the latest `develop`, you can do something like below,
```
% git checkout -b some-branch-name
... (you may work on this branch)
% git push
fatal: The current branch some-branch-name has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin some-branch-name
% git push --set-upstream origin some-branch-name
```

**Comment by MSimoncelli** [comment]
Thanks @atztogo .

I did not realised the presence of the error, since my GitHub was saying that everything was fine (see the green check here https://github.com/MSimoncelli/phono3py/commit/ec1508b155f9d82269ac3af387000cc40fc77be9 ).

Sorry for the inconvenience, I'll look more carefully at the messages on your GitHub next time.
Thanks and best wishes,
Michele

**Comment by atztogo** [comment]
> I did not realise the presence of the error because my GitHub was saying that everything was fine (see the green check here https://github.com/MSimoncelli/phono3py/commit/ec1508b155f9d82269ac3af387000cc40fc77be9 ).

I think this is because you don't use the service https://pre-commit.ci/ on your repository (and you don't need, see as follows). This is an external service out of github, so it is considered configuration is needed per each folk. But after `pre-commit install`, when the git commit, the error should appear on your fold and it prevents committing. So you should be able to realize it. But this is not 100% sure, because it can be system dependent. So the simplest way to check it is to carefully observe the PR but not your push to yoru branch. For example, this PR runs on phonopy/phono3py repository but not your repository, therefore https://pre-commit.ci/  is applied.

But anyway everything went fine now. Thanks for your work!

**Comment by MSimoncelli** [comment]
Thanks for the clarifications, I will keep this in mind for the future!

**Pull request merged**
