### PR TITLE
Update setup.py for macOS environment

### PR DESCRIPTION
**Pull request by atztogo**
This is minor update of `setup.py` after PR #59 to make it work for macOS and OpenMP as default.

### CODE REVIEW

**Comment by zerothi** [comment]
I think this is bad practice, it would be much better to edit the `site.cfg` based on the installation it self.
You are currently hard-coding stuff which is what caused some problems on my end. The `site.cfg` is completely general and allows users to customize at will.

Secondly, I don't know of any compilers that require you to manually add the omp library when you have the `-fopenmp` flag present. So I would say that this PR is not the right direction.

So what problems are you seeing now that isn't covered by a `site.cfg` edit?

**Comment by zerothi** [comment]
The whole point for #59 was to remove hardcoded stuff ;)

**Comment by zerothi** [comment]
If anything you just want to check which compiler you are using to get the openmp flag and put that flag on the link and compile args as well. I think that would be an ok thing.

**Comment by atztogo** [comment]
At least on my environment, only `-fopenmp` didn't work. Many users may not be able to modify `site.cfg`. So at least following the installation page with conda, I want to make `pip install -e .` works. Otherwise I will get many questions. Do you have any idea how to make it?

**Comment by zerothi** [comment]
> At least on my environment, only `-fopenmp` didn't work. Many users may not be able to modify `site.cfg`. So at least following the installation page with conda, I want to make `pip install -e .` works. Otherwise I will get many questions. Do you have any idea how to make it?

Did you also put `-fopenmp` in the linker flags?

**Comment by atztogo** [comment]
Sorry. If I write it in `site.cfg`, it worked (some magic?). I am still in Stone Age.

Do you think it is acceptable to have the following `site.cfg` as default?
```
[phono3py]
extra_compile_args = -fopenmp
```

**Comment by zerothi** [comment]
> Sorry. If I write it in `site.cfg`, it worked (some magic?). I am still in Stone Age.
> 
> Do you think it is acceptable to have the following `site.cfg` as default?
> 
> ```
> [phono3py]
> extra_compile_args = -fopenmp
> ```

The `site.cfg` is read by numpy distutils. And that was the hole purpose of #59. This `site.cfg` may also be located in the user home see the header [here](https://github.com/numpy/numpy/blob/main/site.cfg.example).

I would _not_ recommend putting a default `site.cfg` since your current one will not work for intel where the flag is `-qopenmp`.

**Comment by atztogo** [comment]
OK. I mostly reverted.

I can not see how the following lines work. Could you tell me?
```python
if "--with-threaded-blas" in sys.argv:
    del sys.argv["--with-threaded-blas"]
    with_threaded_blas = True

if "--with-mkl" in sys.argv:
    del sys.argv["--with-mkl"]
    with_mkl = True
    # MKL generally uses multi-threaded blas
    with_threaded_blas = True
```

**Comment by atztogo** [comment]
Are the following lines necessary?
```python
extra_compile_args = ""
extra_link_args = extra_compile_args
```

**Comment by zerothi** [comment]
> OK. I mostly reverted.
> 
> I can not see how the following lines work. Could you tell me?
> 
> ```python
> if "--with-threaded-blas" in sys.argv:
>     del sys.argv["--with-threaded-blas"]
>     with_threaded_blas = True
> 
> if "--with-mkl" in sys.argv:
>     del sys.argv["--with-mkl"]
>     with_mkl = True
>     # MKL generally uses multi-threaded blas
>     with_threaded_blas = True
> ```

They are used to append the manual flags in the `macros` variable. So they affect the compilation of the sources. Perhaps if you want them by default to be *on* you should add flags that can turn them off. :)
I agree, they are not really used for anything, so they should probably just be deleted.

**Comment by zerothi** [comment]
> Are the following lines necessary?
> 
> ```python
> extra_compile_args = ""
> extra_link_args = extra_compile_args
> ```

No, they can be deleted. :)

**Comment by atztogo** [comment]
Thank you!

**Pull request merged**
